# ============================================================
# STACK SWARM — Plataforma 360 CRM
# Cole no Portainer → Stacks → Add Stack → Web Editor
# Compatível com Docker Swarm Mode
# ============================================================
version: "3.8"

# Variáveis de ambiente compartilhadas entre app, queue e reverb
x-app-env: &app-env
  APP_NAME: "Plataforma 360"
  APP_ENV: production
  APP_DEBUG: "false"
  APP_TIMEZONE: America/Sao_Paulo
  APP_URL: https://syncro.matheusrossi.com.br
  ASSET_URL: https://syncro.matheusrossi.com.br
  APP_KEY: "base64:yyrXOSQTQq6MYA7fk0+1YHOUkslOvswrHifAomKMGGU="
  APP_LOCALE: pt_BR
  APP_FALLBACK_LOCALE: pt_BR
  APP_FAKER_LOCALE: pt_BR
  APP_MAINTENANCE_DRIVER: file
  BCRYPT_ROUNDS: "12"
  LOG_CHANNEL: stack
  LOG_STACK: single
  LOG_LEVEL: warning
  DB_CONNECTION: mysql
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_DATABASE: plataforma360
  DB_USERNAME: crm
  DB_PASSWORD: "60588c0273caac3cc637a65b6af4dc60"
  SESSION_DRIVER: redis
  SESSION_LIFETIME: "120"
  SESSION_ENCRYPT: "false"
  SESSION_PATH: /
  SESSION_DOMAIN: "null"
  SESSION_SECURE_COOKIE: "true"
  SESSION_HTTP_ONLY: "true"
  SESSION_SAME_SITE: lax
  BROADCAST_CONNECTION: reverb
  FILESYSTEM_DISK: local
  QUEUE_CONNECTION: redis
  CACHE_STORE: redis
  CACHE_PREFIX: crm_
  REDIS_CLIENT: phpredis
  REDIS_HOST: redis
  REDIS_PASSWORD: "null"
  REDIS_PORT: "6379"
  MAIL_MAILER: log
  MAIL_FROM_ADDRESS: noreply@plataforma360.com.br
  MAIL_FROM_NAME: "Plataforma 360"
  # Reverb — WebSocket server
  REVERB_APP_ID: "crm-app"
  REVERB_APP_KEY: "crm-reverb-key"
  REVERB_APP_SECRET: "crm-reverb-secret"
  # Endereço PÚBLICO (browser → nginx /app/ → reverb:8080)
  REVERB_HOST: "syncro.matheusrossi.com.br"
  REVERB_PORT: "443"
  REVERB_SCHEME: "https"
  # Endereço INTERNO Docker (PHP app→reverb via crm_private, sem TLS)
  REVERB_SERVER_HOST: "reverb"
  REVERB_SERVER_PORT: "8080"
  REVERB_SERVER_SCHEME: "http"
  # Vite Reverb (para build do frontend)
  VITE_REVERB_APP_KEY: "crm-reverb-key"
  VITE_REVERB_HOST: "syncro.matheusrossi.com.br"
  VITE_REVERB_PORT: "443"
  VITE_REVERB_SCHEME: "https"
  # WAHA
  WAHA_BASE_URL: https://waha.matheusrossi.com.br
  WAHA_API_KEY: "faf5b83c9d4a9b913c9f7ecbf3da2b50"
  WAHA_WEBHOOK_SECRET: "KFq4eBE7EJ2aDRneKtm0ke7jg2GDFMOU"
  # OAuth
  FACEBOOK_CLIENT_ID: ""
  FACEBOOK_CLIENT_SECRET: ""
  FACEBOOK_REDIRECT_URI: https://syncro.matheusrossi.com.br/oauth/facebook/callback
  FACEBOOK_API_VERSION: v19.0
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""
  GOOGLE_REDIRECT_URI: https://syncro.matheusrossi.com.br/oauth/google/callback
  GOOGLE_DEVELOPER_TOKEN: ""
  GOOGLE_ADS_API_VERSION: v16
  WHATSAPP_VERIFY_TOKEN: plataforma360_whatsapp_verify
  WHATSAPP_PHONE_NUMBER_ID: ""
  WHATSAPP_BUSINESS_ACCOUNT_ID: ""
  WHATSAPP_ACCESS_TOKEN: ""

services:

  # ────────────────────────────────────────────────────────
  # NGINX — roteado pelo Traefik via serverossi
  # ────────────────────────────────────────────────────────
  nginx:
    image: matolado/crm-nginx:latest
    volumes:
      - public_shared:/var/www/public:ro
      - storage_data:/var/www/storage/app/public:ro
    networks:
      - crm_private
      - serverossi
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=serverossi"
        - "traefik.http.routers.crm.rule=Host(`syncro.matheusrossi.com.br`)"
        - "traefik.http.routers.crm.entrypoints=websecure"
        - "traefik.http.routers.crm.tls=true"
        - "traefik.http.routers.crm.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.crm.loadbalancer.server.port=80"
        - "traefik.http.routers.crm-http.rule=Host(`syncro.matheusrossi.com.br`)"
        - "traefik.http.routers.crm-http.entrypoints=web"
        - "traefik.http.routers.crm-http.middlewares=https-redirect@docker"

  # ────────────────────────────────────────────────────────
  # APP — PHP-FPM Laravel
  # ────────────────────────────────────────────────────────
  app:
    image: matolado/crm:latest
    environment:
      <<: *app-env
    volumes:
      - public_shared:/var/www-public
      - storage_data:/var/www/storage/app
      - logs_data:/var/www/storage/logs
      - cache_data:/var/www/bootstrap/cache
    networks:
      - crm_private
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 10s

  # ────────────────────────────────────────────────────────
  # QUEUE — Worker Laravel
  # ────────────────────────────────────────────────────────
  queue:
    image: matolado/crm:latest
    command: >
      bash -c "
        rm -f /var/www/bootstrap/cache/packages.php &&
        php artisan package:discover --ansi 2>/dev/null || true &&
        php artisan queue:work redis
          --queue=whatsapp,default
          --tries=3
          --backoff=5
          --sleep=3
          --timeout=60
          --memory=256
      "
    environment:
      <<: *app-env
    volumes:
      - storage_data:/var/www/storage/app
      - logs_data:/var/www/storage/logs
      - cache_data:/var/www/bootstrap/cache
    networks:
      - crm_private
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 15s

  # ────────────────────────────────────────────────────────
  # REVERB — WebSocket server
  # O nginx já tem /app/ e /apps/ fazendo proxy para reverb:8080.
  # memory: 256M evita que o OS OOM Killer mate o processo —
  # Docker gerencia o restart limpo ao invés do OOM Killer.
  # ────────────────────────────────────────────────────────
  reverb:
    image: matolado/crm:latest
    command: >
      bash -c "
        rm -f /var/www/bootstrap/cache/packages.php &&
        php artisan package:discover --ansi 2>/dev/null || true &&
        php artisan reverb:start --host=0.0.0.0 --port=8080
      "
    environment:
      <<: *app-env
    volumes:
      - storage_data:/var/www/storage/app
      - logs_data:/var/www/storage/logs
      - cache_data:/var/www/bootstrap/cache
    networks:
      - crm_private
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 10s
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 64M

  # ────────────────────────────────────────────────────────
  # MYSQL 8.0
  # ────────────────────────────────────────────────────────
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "0f6e6767fff792721c91f8e0c783b082"
      MYSQL_DATABASE: plataforma360
      MYSQL_USER: crm
      MYSQL_PASSWORD: "60588c0273caac3cc637a65b6af4dc60"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - crm_private
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p0f6e6767fff792721c91f8e0c783b082"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager   # garante que MySQL sempre rode no mesmo nó (dados persistentes)

  # ────────────────────────────────────────────────────────
  # REDIS 7
  # ────────────────────────────────────────────────────────
  redis:
    image: redis:7-alpine
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    networks:
      - crm_private
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager

# ── Volumes ───────────────────────────────────────────────
volumes:
  mysql_data:
  redis_data:
  storage_data:
  logs_data:
  cache_data:
  public_shared:

# ── Redes ─────────────────────────────────────────────────
networks:
  crm_private:
    driver: overlay      # overlay obrigatório no Swarm
    attachable: true
  serverossi:
    external: true
    name: serverossi
